#+TITLE: JRenamer

* Intro
JRenamer is a renaming tool that allows for the composition of arbitrary, script-generated fragments into new names.

* Usage
You must supply a list of input files
#+begin_src
jrenamer file.txt other_file.txt
#+end_src

This alone will visit these files and extract metadata such as ~filename~ and the ~created~ date.
It will display the list of these fragments for each file, from which you can compose the new filename using the following syntax.

: #filename#_#created#

Keys of fragments are surrounded by 2 ~#~ signs, to display an actual ~#~ sign, please use ~##~.

** Script Extension
Any number of scripts (python at the moment) can be set to run on the command line
#+begin_src
jrenamer file.txt other_file.txt -s gps_getter.py
#+end_src

A script should accept a map of fragments, and return new fragments to add to the total map.
Using this, you can build up a list of fragments to use in the final filename allocation

*** Example
Say our ~gps_getter.py~ can extract the GPS co-ordinates out of a file accessing it via the ~filename~ fragment, it should then print to the stdout a JSON object in the form
#+begin_src json
{"gps_longitude": "37.62", "gps_latitude: "55.75"}
#+end_src

*** Write your own!
The intent of this program is to offload custom renaming work to scripts, so if you have a specific need, whip up a quick script and combine the fragments!
There is an example script called ~example_script.py~ distributed with the source to get you going.

** Batch Mode
Instead of user input, you can supply your format string at the command invocation with the ~-f/--format~ switch and it will be used.
#+begin_src
jrenamer file.txt other_file.txt -s gps_getter.py --format "#filesize#_#gps_longitude#"
#+end_src
